name: CI
on:
    push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
    
      - name: Install python
        run: uv python install

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Format
        run: uv run ruff format --check

      - name: Lint
        run: uv run ruff check

      - name: Type check
        run: uv run mypy .
